version: '3'

services:
  postgresdb:
    image: 'bitnami/postgresql:16.0.0'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=exmeal_dev
    ports:
      - 5432:5432
    volumes:
      - 'postgres_data:/bitnami/postgresql'

volumes:
  postgres_data:
